version: 2
jobs:
  test:
    docker:
      - image: durosoft/crystal-alpine
    steps:
      - checkout
      - run: shards install
      - run: crystal spec
workflows:
  version: 2
  test:
    jobs:
      - test
