version: 2
jobs:
  test:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install curl wget git docker build-essential zlib1g-dev libssl-dev libpcre3-dev libevent-dev -y
      - run: wget -O crystal.tar.gz https://github.com/crystal-lang/crystal/releases/download/0.25.0/crystal-0.25.0-1-linux-x86_64.tar.gz
      - run: tar -zxf crystal.tar.gz
      - run: crystal-0.25.0-1/bin/shards install
      - run: crystal-0.25.0-1/bin/crystal spec
workflows:
  version: 2
  test:
    jobs:
      - test
